from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1233, 700)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 221, 611))
        self.widget.setObjectName("widget")
        self.Adminlabel = QtWidgets.QLabel(parent=self.widget)
        self.Adminlabel.setGeometry(QtCore.QRect(30, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Adminlabel.setFont(font)
        self.Adminlabel.setObjectName("Adminlabel")
        self.ServiceButton = QtWidgets.QPushButton(parent=self.widget)
        self.ServiceButton.setGeometry(QtCore.QRect(0, 80, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ServiceButton.setFont(font)
        self.ServiceButton.setObjectName("ServiceButton")
        self.ScheduleButton = QtWidgets.QPushButton(parent=self.widget)
        self.ScheduleButton.setGeometry(QtCore.QRect(0, 120, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ScheduleButton.setFont(font)
        self.ScheduleButton.setObjectName("ScheduleButton")
        self.ClientsButton = QtWidgets.QPushButton(parent=self.widget)
        self.ClientsButton.setGeometry(QtCore.QRect(0, 160, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ClientsButton.setFont(font)
        self.ClientsButton.setObjectName("ClientsButton")
        self.TrainerButton = QtWidgets.QPushButton(parent=self.widget)
        self.TrainerButton.setGeometry(QtCore.QRect(0, 200, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TrainerButton.setFont(font)
        self.TrainerButton.setObjectName("TrainerButton")
        self.HallButton = QtWidgets.QPushButton(parent=self.widget)
        self.HallButton.setGeometry(QtCore.QRect(0, 240, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.HallButton.setFont(font)
        self.HallButton.setObjectName("HallButton")
        self.ReportButton = QtWidgets.QPushButton(parent=self.widget)
        self.ReportButton.setGeometry(QtCore.QRect(0, 280, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ReportButton.setFont(font)
        self.ReportButton.setObjectName("ReportButton")
        self.ExitButton = QtWidgets.QPushButton(parent=self.widget)
        self.ExitButton.setGeometry(QtCore.QRect(40, 550, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ExitButton.setFont(font)
        self.ExitButton.setObjectName("ExitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1233, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Adminlabel.setText(_translate("MainWindow", "Админ-панель"))
        self.ServiceButton.setText(_translate("MainWindow", "Услуги"))
        self.ScheduleButton.setText(_translate("MainWindow", "Расписание"))
        self.ClientsButton.setText(_translate("MainWindow", "Клиенты"))
        self.TrainerButton.setText(_translate("MainWindow", "Тренеры"))
        self.HallButton.setText(_translate("MainWindow", "Залы"))
        self.ReportButton.setText(_translate("MainWindow", "Отчеты"))
        self.ExitButton.setText(_translate("MainWindow", "Выход"))
