from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ServiceWindow(object):
    def setupUi(self, ServiceWindow):
        ServiceWindow.setObjectName("ServiceWindow")
        ServiceWindow.resize(1233, 700)
        self.centralwidget = QtWidgets.QWidget(parent=ServiceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 221, 611))
        self.widget.setObjectName("widget")
        self.Adminlabel = QtWidgets.QLabel(parent=self.widget)
        self.Adminlabel.setGeometry(QtCore.QRect(30, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Adminlabel.setFont(font)
        self.Adminlabel.setObjectName("Adminlabel")
        self.ServiceButton = QtWidgets.QPushButton(parent=self.widget)
        self.ServiceButton.setGeometry(QtCore.QRect(0, 80, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ServiceButton.setFont(font)
        self.ServiceButton.setObjectName("ServiceButton")
        self.ScheduleButton = QtWidgets.QPushButton(parent=self.widget)
        self.ScheduleButton.setGeometry(QtCore.QRect(0, 120, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ScheduleButton.setFont(font)
        self.ScheduleButton.setObjectName("ScheduleButton")
        self.ClientsButton = QtWidgets.QPushButton(parent=self.widget)
        self.ClientsButton.setGeometry(QtCore.QRect(0, 160, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ClientsButton.setFont(font)
        self.ClientsButton.setObjectName("ClientsButton")
        self.TrainerButton = QtWidgets.QPushButton(parent=self.widget)
        self.TrainerButton.setGeometry(QtCore.QRect(0, 200, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TrainerButton.setFont(font)
        self.TrainerButton.setObjectName("TrainerButton")
        self.HallButton = QtWidgets.QPushButton(parent=self.widget)
        self.HallButton.setGeometry(QtCore.QRect(0, 240, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.HallButton.setFont(font)
        self.HallButton.setObjectName("HallButton")
        self.ReportButton = QtWidgets.QPushButton(parent=self.widget)
        self.ReportButton.setGeometry(QtCore.QRect(0, 280, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ReportButton.setFont(font)
        self.ReportButton.setObjectName("ReportButton")
        self.ExitButton = QtWidgets.QPushButton(parent=self.widget)
        self.ExitButton.setGeometry(QtCore.QRect(40, 550, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ExitButton.setFont(font)
        self.ExitButton.setObjectName("ExitButton")
        self.TableService = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.TableService.setGeometry(QtCore.QRect(260, 120, 611, 451))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TableService.setFont(font)
        self.TableService.setColumnCount(4)
        self.TableService.setObjectName("TableService")
        self.TableService.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableService.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableService.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableService.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableService.setHorizontalHeaderItem(3, item)
        self.TableService.horizontalHeader().setDefaultSectionSize(150)
        self.TableService.horizontalHeader().setMinimumSectionSize(50)
        self.TableService.verticalHeader().setDefaultSectionSize(50)
        self.TableService.verticalHeader().setMinimumSectionSize(50)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 587, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        ServiceWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ServiceWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1233, 26))
        self.menubar.setObjectName("menubar")
        ServiceWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ServiceWindow)
        self.statusbar.setObjectName("statusbar")
        ServiceWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ServiceWindow)
        QtCore.QMetaObject.connectSlotsByName(ServiceWindow)

    def retranslateUi(self, ServiceWindow):
        _translate = QtCore.QCoreApplication.translate
        ServiceWindow.setWindowTitle(_translate("ServiceWindow", "MainWindow"))
        self.Adminlabel.setText(_translate("ServiceWindow", "Админ-панель"))
        self.ServiceButton.setText(_translate("ServiceWindow", "Услуги"))
        self.ScheduleButton.setText(_translate("ServiceWindow", "Расписание"))
        self.ClientsButton.setText(_translate("ServiceWindow", "Клиенты"))
        self.TrainerButton.setText(_translate("ServiceWindow", "Тренеры"))
        self.HallButton.setText(_translate("ServiceWindow", "Залы"))
        self.ReportButton.setText(_translate("ServiceWindow", "Отчеты"))
        self.ExitButton.setText(_translate("ServiceWindow", "Выход"))
        item = self.TableService.horizontalHeaderItem(0)
        item.setText(_translate("ServiceWindow", "Вид услуги"))
        item = self.TableService.horizontalHeaderItem(1)
        item.setText(_translate("ServiceWindow", "Зал"))
        item = self.TableService.horizontalHeaderItem(2)
        item.setText(_translate("ServiceWindow", "Макс. человек"))
        item = self.TableService.horizontalHeaderItem(3)
        item.setText(_translate("ServiceWindow", "стоимость"))
        self.pushButton.setText(_translate("ServiceWindow", "Добавить"))
