# Form implementation generated from reading ui file 'src\ui\generated_ui\login_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 506)
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Autorization = QtWidgets.QLabel(parent=self.centralwidget)
        self.Autorization.setGeometry(QtCore.QRect(190, 30, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Autorization.setFont(font)
        self.Autorization.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.Autorization.setScaledContents(True)
        self.Autorization.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Autorization.setWordWrap(False)
        self.Autorization.setObjectName("Autorization")
        self.Input = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Input.setGeometry(QtCore.QRect(290, 310, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Input.setFont(font)
        self.Input.setObjectName("Input")
        self.Email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Email.setGeometry(QtCore.QRect(160, 140, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Email.setFont(font)
        self.Email.setInputMask("")
        self.Email.setObjectName("Email")
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setGeometry(QtCore.QRect(160, 230, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setObjectName("password")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.Autorization.setText(_translate("LoginWindow", "Авторизация в системе"))
        self.Input.setText(_translate("LoginWindow", "Вход"))
        self.Email.setPlaceholderText(_translate("LoginWindow", "email"))
        self.password.setPlaceholderText(_translate("LoginWindow", "пароль"))
